### ISSUE TITLE
Backup issue

### ISSUE THREAD

**Issue by kookma** [ibnishak/Timimi#1]
Great chrome add on!
Just there is no backup! Is it possible to have a small control panel when click on the fish icon to set an interval for making backup?

This is very important to keep wikis from sudden crash or unwanted changes!

Thanks again for all your efforts

**Comment by ibnishak** [comment]
Added to roadmap.

**Comment by ibnishak** [comment]
Please see [Snapshot plugin](https://ibnishak.github.io/Tesseract/pluginsandmacros/snapshot.html)

**Comment by kookma** [comment]
Great job!
thanks
