### ISSUE TITLE
install-linux-firefox fails if run from different file system than ~/

### ISSUE THREAD

**Issue by studio315b** [ibnishak/Timimi#11]
Because Go's `os.rename` does not work across file systems, attempting to install from a seperate file system (such as a usb drive or the HDD in a SSD+HDD setup) fails with the following error:

`2018/12/26 12:53:49 Move: rename timimi /home/somkun/.mozilla/native-messaging-hosts/timimi: invalid cross-device link`

### Repro Steps

1. Download the linux install package from [release 2.0.2](https://github.com/ibnishak/Timimi/releases/tag/v2.0.2) to a non-os drive (flash drive, or 2nd HDD work)
2. Extract all
3. Run install-linux-firefox

### Expected
```
Hello There
Starting Timimi Installation
Created host directory: /home/somkun/.mozilla/native-messaging-hosts
Created host manifest: /home/somkun/.mozilla/native-messaging-hosts/timimi.json
Created host executable: /home/somkun/.mozilla/native-messaging-hosts/timimi
```

### Actual
```
Hello There
Starting Timimi Installation
Created host directory: /home/somkun/.mozilla/native-messaging-hosts
Created host manifest: /home/somkun/.mozilla/native-messaging-hosts/timimi.json
2018/12/26 12:53:49 Move: rename timimi /home/somkun/.mozilla/native-messaging-hosts/timimi: invalid cross-device link

```

I don't have my dev machine available to make a PR at the moment, but the fix should be pretty easy. If rename fails, we should copy then delete instead. That should work across file systems.

**Comment by ibnishak** [comment]
Thank you for issue. I will definitely look into it.

**Comment by ibnishak** [comment]
Sorry, accidently closed the issue.

**Comment by eracap** [comment]
I do have this problem in Firefox 58.0.2 on my linux system (kde neon). Is there a fix?

**Comment by eracap** [comment]
Sorry I mean Firefox 68.0.2

**Comment by eracap** [comment]
> I do have this problem in Firefox 68.0.2 on my linux system (kde neon). Is there a fix?

Now I've solved this by running install-linux-firefox from the Firefox user's folder.

**Comment by ibnishak** [comment]
In version 2.1, the installer copies the executable byte for byte instead of renaming. Please check and see if it closes the issue.
