### ISSUE TITLE
Not saving on Win10 FFv64

### ISSUE THREAD

**Issue by CodaCodr** [ibnishak/Timimi#12]
Like the title says...

Win10, Firefox v64

This is a shiny new Firefox install so there are no likely add-on clashes.

The files are located on the local hard disk C: but the locations are "mapped" to drives like W: and P:

Tiddlywiki "Saved" notification appears but the file on disk is not updated.

Tried: Enabling and disabling backups. Same result.
Tried: Enabling and disabling Scripts. Same result.

Here are the messages posted to the console:

```
saver-handler: Saving wiki with method save through saver tiddlyfox $:/core/modules/utils/logger.js
Message ID is tiddlywiki-save-file-response-3 
```

**Comment by ibnishak** [comment]
I hope it is saving now!
