### ISSUE TITLE
Saving in Firefox Portable not working?

### ISSUE THREAD

**Issue by Suzy1970** [ibnishak/Timimi#15]
When I save a Tiddly, or changes to it, it initially shows as saved in the "Recent" sidebar tab, but when I refresh the wiki, this vanishes and nothing has been saved. Also no backups are being created, though I have made a folder for them. (System: Windows 8.1, Firefox Quantum portable 64.0.2 64-bit, Portable Apps version)

**Comment by ibnishak** [comment]
I think it might not be possible to do this. The portable version of Firefox might not have access to windows registry, which is necessary for all Quantum versions of Firefox.

**Comment by Suzy1970** [comment]
I think I have resolved the issue - I only installed the browser add-on, not the timimi-windows-installer.exe as well (as described in https://ibnishak.github.io/Timimi/#Installing%20Timimi). After installing the Windows .exe, my Tiddlywiki seems to be saving and retaining the changes - so I'll mark this issue as resolved (if nothing else comes up)?

**Comment by ibnishak** [comment]
That is actually educational. As I said, I was under the impression that portable version does not have access to registry. Thank you.
