### ISSUE TITLE
Roaming directory does not allow executable files in Windows

### ISSUE THREAD

**Issue by aaarciniega** [ibnishak/Timimi#16]
Due to security issues, putting executable files in the Roaming directory is not allowed in my business environment. Editing the registry is feasible though.

When the new Chrome be released, would it be possible to have the .exe, .json, and other files in a flash drive and the registry line include the path to the flash drive?

**Comment by ibnishak** [comment]
I ll see if it is possible.

**Comment by ibnishak** [comment]
In the installer for the version 2.1 which supports chrome, you can choose the location of executables and JSON. You will have to edit the registry manually though.
