### ISSUE TITLE
Android Firefox Platform One day?

### ISSUE THREAD

**Issue by AnthonyMuscio** [ibnishak/Timimi#18]
Hi, 
I just wanted to point out It would be nice if we could get Timimi for FireFox on Android and or iPhones 

No Pressure, Just thought it worthy of mention and perhaps finding some insight to the new methods on the mobile platform.

Regards
Tony

**Comment by ibnishak** [comment]
Android platform does not allow native extensions and Google or Mozilla has not announced any definite plans regarding the same. Will reopen if status changes.
