### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by raffow** [ibnishak/Timimi#19]
I'am trying to install Timimi on Ubuntu. After `./install-linux-firefox` I get

`bash: ./install-linux-firefox: cannot execute binary file: Exec format error`

Does Timimi only work on 64-bit systems?

**Comment by ibnishak** [comment]
Yes, timimi is only built for 64 bit systems

**Comment by raffow** [comment]
Thanks. Might be worth mentioning on the Wiki-Page

**Comment by ibnishak** [comment]
I have update this information in Readme.

**Comment by monomycelium** [comment]
i am running asahi linux on an m1 machine (`arch linux arm aarch64`). when I execute `timimi-2-1-1-Linux`, I get this:

```
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing   100%  
./timimi-2-1-1-Linux.sh: line 653: ./installer: cannot execute binary file: Exec format error
```

is the linux installer only for x86? can i recompile myself? i've posted an issue on #83 about this.

**Comment by monomycelium** [comment]
> Does Timimi only work on 64-bit systems?

Not exactly. Timimi can be built for `aarch64` Linux, and probably also for any other architecture that can build `go` software. See my comment [here](https://github.com/ibnishak/Timimi/issues/25#issuecomment-1278368435) to build Timimi on your Unix machine.

> Yes, timimi is only built for 64 bit systems

That is pretty vague, as the Timimi binaries in the release page are not built for `aarch64` Linux, which is indeed 64-bit. Instead, the binaries are built for `x86_64`, also known as `amd64`.
