### ISSUE TITLE
Documentation Revision for Windows 7 

### ISSUE THREAD

**Issue by TiddlyTweeter** [ibnishak/Timimi#2]
Docs at [Readme.md](https://github.com/ibnishak/Timimi)  read ...

> Supported OS
>     OSX
>     Windows >7

Actually Windows 7 works with it. Did you mean ...

Windows 7+  ?

**Comment by ibnishak** [comment]
Will update in the next commit.

**Comment by ibnishak** [comment]
Update to reflect the status of windows 7
