### ISSUE TITLE
Extended saving features

### ISSUE THREAD

**Issue by AnthonyMuscio** [ibnishak/Timimi#21]
Hi, I have being working with other savers and hosting mechanisms of late including the new local storage plugin. I had the following idea you may be interested in, to extend Timimi or introduce a new FireFox plugin. This is purely optional and if you are interested.

**Background**
There are limitations to the local storage plugin, it does not save to the original file but into temporary browser storage which is not guaranteed.  However it basically makes it possible for a user to save changes to any wiki read only or otherwise hosted at a http/s address. Timimi effectively does the same for TiddlyWiki files found at a File:// address. It works very well and leverages the new services available in modern browsers.

**Idea**
Would it be feasible for Timimi or another plugin to identify Tiddlywikis found at a URI rather than only at a file address and offer the facility to save the wiki (or only the changes) to a permanent local storage equivalent? Returning to the same address would lookup the local storage and import it as does the local storage plugin. A facility to save to disk the served wiki plus changes or not, would also be a great feature. This will need to be sellectable similar to the old tiddlyfox such as when TiddlyWikis are on a host which can save the wiki it can be switched off.

**Why**
With such a plugin TiddlyWiki users will be able to "Save to" any wiki on the internet or open any file based wiki with out any concern for the saving mechanism in use. This would enhance adoption perhaps more than any other saving mechanism ever for TiddlyWiki, which Timimi already comes close to doing.

**Useful notes ?**
- The ability to nominate on/or off for automatically saving when finding a Wiki
- The ability to generate a message on provision of the save facility
- - eg; This is a TiddlyWiki site, would you like to save changes to a permanent local storage ?

Just dreaming
Tony

**Comment by ibnishak** [comment]
That is a great idea. I am of the opinion that it should be a different plugin. I am firm believer of Unix philosophy - one tool, one job.
