### ISSUE TITLE
Post intalation steps are not clear in docs

### ISSUE THREAD

**Issue by JasoonS** [ibnishak/Timimi#22]
I have installed the plugin on firefox 66 on ubuntu. I have also ran the command `./install-linux-firefox` and it worked without error.

I'm just unsure of what to do next. (I have tried running the `./timimi` binary, but it doesn't seem to do anything.)

How do I tell the plugin where my tiddlers are (on the file system)? How do I open those tiddlers in the browser?

When I work it all out I'd be more than happy to make a PR making the explanation clearer for anyone else.

**Comment by ibnishak** [comment]
Timimi plugin is modelled after former tiddlyfox plugin. So its use case is to save standalone tiddlywiki html files, not tiddlers.

As for standalone tiddlywiki html files, you need not do anything further. Open files in your browser, make some changes and save. Timimi will automatically save the file in the original location, wherever the file is.

**Comment by ibnishak** [comment]
@JasoonS Did you figure out your issue?

**Comment by JasoonS** [comment]
Hi @ibnishak  Sorry for not getting back to you!

Yes, the problem is that I was using tiddly server. Rather than the tiddlywiki html file.

**Comment by ibnishak** [comment]
In the updated Readme and documents, this is made clear more thoroughly.
