### ISSUE TITLE
Backup folder not created with correct permission (macOS)

### ISSUE THREAD

**Issue by PengjuYan** [ibnishak/Timimi#28]
Reproduce (macOS, TWC, FireFox) (I guess this issue does not apply only to TWC files):

1. Suppose there is no a folder named "backup" relative to your TWC file.

2. Set the "Backup location" to be "backup".

3. Open a TWC file in FireFox, save it.

4. You can see a new folder "backup" created, but there's no backup files saved there. The reason is that the new folder is created without the "x" permission.

**Comment by ibnishak** [comment]
Timimi backup mechanism does not support the TWC yet. The support for TWC is minimal at this point.

**Comment by PengjuYan** [comment]
@ibnishak Hi, this issue occurs for TW5 as well. That is to say, it occurs for macOS and FireFox, no matter whether it's a TWC or a TW5.

**Comment by ibnishak** [comment]
I have [fixed this issue](https://github.com/ibnishak/Timimi/blob/c06883f7ded15ccce5a231e70f73b8a146ae1120/host/utils.go#L15) in the latest release. Can you please check and give feedback.

**Comment by PengjuYan** [comment]
@ibnishak Thank you very much Rizwan. I've verified the fix with the setting: TWC 2.9.2 + Firefox 75.0 + macOS Catalina (10.15.4).
