### ISSUE TITLE
Installer "Bad substitution" error (with Linux + Firefox)

### ISSUE THREAD

**Issue by erwanm** [ibnishak/Timimi#3]
Using Ubuntu 18.04, running the install script `install-linux-mac-firefox.sh` gives the following error: 

```
./install-linux-mac-firefox.sh: 28: ./install-linux-mac-firefox.sh: Bad substitution
```

I found that a simple solution would be to replace the separators for sed by another character than `/`, for instance `*` (since it's very unlikely to appear in a path). This way there's no need to protect the slashes.

```
HOST_PATH="$TARGET_DIR/$HOST_NAME.py"
#ESCAPED_HOST_PATH=${HOST_PATH////\\/}
sed -i -e "s*HOST_PATH*$HOST_PATH*" "$TARGET_DIR/$HOST_NAME.json"
```

**Comment by ibnishak** [comment]
Please check the new release and see if the problem remains. 

https://ibnishak.github.io/Timimi/#Installing%20Timimi

**Comment by ibnishak** [comment]
Closing as the issue pertains to older version and timimi 2.0 onwards `sed` is not used in installer.
