### ISSUE TITLE
Saving large wikis freezes computer with Firefox 70.0.1 

### ISSUE THREAD

**Issue by malgam** [ibnishak/Timimi#33]
With Firefox 70.0.1 (64-bit), saving takes a long time (~20s) and freezes the computer (no keyboard or mouse response) when saving large Tiddlywikis.  The wiki size threshold seems to be about 26MB on my Ubuntu laptop with about 8GB of RAM.  Below this size, saving works fine.  There is some evidence that computers with more RAM do not have the same problem (or maybe the size threshold is higher).  See this discussion in the [Tiddlywiki forum](https://groups.google.com/forum/#!topic/tiddlywiki/-o57DXvDt5A).

I've seen the same problem with a Macbook running FF 70.0.1.

With FF version 68.2.0esr on the Ubuntu laptop, my large wikis save normally.

**Comment by ibnishak** [comment]
Hi there Mal,
Big fan of many of your works.

I just tested with 80 MB wiki on Firefox 71.0b11 (64-bit) Arch Linux. My system has 6GB RAM and it saved without hitches. The back-end of timimi is build to save anything under 200MB in 1 sec or less. I have to thoroughly compare the changes between Firefox builds to get to the bottom of this,

I am slightly parched for time as of now. Hence the lack of updates and fixes. Once I get some time, I promise to look into it more closely. 

Sincerely,
Riz

**Comment by malgam** [comment]
Hi Riz,

I just installed the snap package of FF build 71.0b12-1 on my Ubuntu laptop and it also seems to be saving large wikis with no problems.  I guess there was some issue with the 70.0.1 release that has already been fixed, so you may not need to spend any time on this.

Thanks for responding.

Regards,
Mal

**Comment by ibnishak** [comment]
Oh, that s great then
