### ISSUE TITLE
Tower of Hanoi - backup description seem to be "strange"!

### ISSUE THREAD

**Issue by pmario** [ibnishak/Timimi#39]
Please have a look at:  https://en.wikipedia.org/wiki/Backup_rotation_scheme#Tower_of_Hanoi

What you describe is something [completely different](https://ibnishak.github.io/Timimi/#Tower%20of%20Hanoi). Please fix the description or the functionality.

**Comment by ibnishak** [comment]
I have changed the description and mentioned that it is a variation of the original concept.
