### ISSUE TITLE
Ubuntu 18.04 + Firefox: not saving

### ISSUE THREAD

**Issue by erwanm** [ibnishak/Timimi#4]
The extension seems correctly installed in Firefox, and I can see the "saved wiki" message when I try to save, but the changes are not written to the file.

Content of `$HOME/.mozilla/native-messaging-hosts/timimi.json` is:

```
{
  "name": "timimi",
  "description": "Native messaging host to save TW5",
  "path": "/home/erwan/.mozilla/native-messaging-hosts/timimi.py",
  "type": "stdio",
  "allowed_extensions": [ "timimi@tesseract.com" ]
}
```

Let me know if there's more info I can provide

**Comment by ibnishak** [comment]
Can you tell me the python version installed?

**Comment by erwanm** [comment]
Python 2.7.15rc1

**Comment by erwanm** [comment]
Ok, apparently python3 is also installed (by default I think, I don't remember installing it).

So all I had to do was change the shebang the way you said, and now it works perfectly well!

Thanks a lot!
