### ISSUE TITLE
Feature Request: Microsoft Edge (Chromium Support)

### ISSUE THREAD

**Issue by kookma** [ibnishak/Timimi#41]
I see you have added support for Chrome, that is wonderful and much appreciated!
With the new release of Microsoft Edge which is based on Chromium I may recommend to add Edge-add-on. I know Chrome add-ons are supported by Edge!

Eagerly waiting for new release!

**Comment by ibnishak** [comment]
In a few days I will checkout the requirements for Microsoft store and try to push it there. Otherwise I am glad to know that the extension works in Edge(Chromium)

**Comment by kookma** [comment]
The Microsoft Edge allows to open Chrome Store and install from there, so I close this issue!
