### ISSUE TITLE
Extension Settings on Chrome

### ISSUE THREAD

**Issue by kookma** [ibnishak/Timimi#42]
On Chrome Extension Options saved but when you reopen the Options window nothing is displayed seems noting is saved!

This may confuse users! Please check

![Slide-41](https://user-images.githubusercontent.com/830394/80345533-7e090a80-887e-11ea-91f0-97bfd52880ae.png)

This is the picture of options I saved it several times!

**Comment by ibnishak** [comment]
The issue has been resolved in [commit ID c06883f7](https://github.com/ibnishak/Timimi/commit/c06883f7ded15ccce5a231e70f73b8a146ae1120). I have not yet pushed the update to chrome store. I am waiting for a couple of days to see if there are any other bugs. Thereafter will push a bug-fix update.

**Comment by kookma** [comment]
Many Thanks Riz!
