### ISSUE TITLE
Cannot save  - I get the message "Error on contacting timimi host" 

### ISSUE THREAD

**Issue by ybalkind** [ibnishak/Timimi#46]
Hi 

I'm a new user with a fresh install. When I try save I get the message 
"Error on contacting timimi host" 

![image](https://user-images.githubusercontent.com/10196054/81272021-2c663a00-904d-11ea-8f2c-dad348b0e9cb.png)

**Comment by ybalkind** [comment]
Update:

It seems that the program could not install to the default path C:\Users\username\Roaming

So I changed the path and then it did install. Now when I save I get a different error 

"error while saving data by Timimi host. Please check error.log for details." 

I'm not sure where the error.log file is

**Comment by ybalkind** [comment]
Resolved - I figured out that the error.log is actually contained in timimi.log (consider correcting your error message to point to the correct log file?). 
The issue was that I had the incorrect path set for saving the backup.. I corrected this but it still didn't work (with the same error).. So I removed the save path entirely allowing it to save to the default path.. It now works.

With regards to original issue where it failed to save to the \Roaming folder, I wonder if this is because I use a company PC with security restrictions? If so, others may experience the same issue so may be worth making a note about this in your installation guide.

**Comment by ibnishak** [comment]
Yeah sorry about the confusion between error.log and timimi.log. Initially it was named error.log itself. Then I realized other applications might want to use the same name. So I switched the actual filename to "timimi.log" but forgot to correct the notification.

Will mention the writing permission issue in docs. Thanks.
