### ISSUE TITLE
not saving on OSX

### ISSUE THREAD

**Issue by bnash** [ibnishak/Timimi#5]
Hello, this extension would be really useful for me.  

However, I'm having the same issue as described in https://github.com/ibnishak/Timimi/issues/4
but I am using OSX.  I drag and drop timimi-1.4-an+fx.xpi  onto my about:addons page and Timimi seems to be installed.  The "wiki saved" message shows up, but the file isn't saved. 
I tried changing timimi.py to reference python3, as suggested in the other issue, but it didn't work in my case.  Typing  python3 --version gives 
Python 3.6.1 :: Anaconda custom (64-bit)
I'm using Firefox 59.0.1.
My  timimi.json file says
{
  "name": "timimi",
  "description": "Native messaging host to save TW5",
  "path": "HOST_PATH",
  "type": "stdio",
  "allowed_extensions": [ "timimi@tesseract.com" ]
}
Thanks for any suggestions!

**Comment by ibnishak** [comment]
Hi bnash

I am aware that some Mac systems are acting unexpectedly with python3 script. 

However in your case, the native-host is not installed correctly. Can you tell me the folloing things

1. Is timimi.json situated in `/Library/Application Support/Mozilla/NativeMessagingHosts` or `$HOME/Library/Application Support/Mozilla/NativeMessagingHosts`

2. Is timimi.py located in the same folder as timimi.json? They should be.

3. The variable `HOST_PATH` should be substituted with absolute path to `timimi.py`. So it should either look like `/Library/Application Support/Mozilla/NativeMessagingHosts/timimi.py` or `$HOME/Library/Application Support/Mozilla/NativeMessagingHosts/timimi.py` where "$HOME" is the *path to your home directory*

This is something installer should have done automatically. I do not know what went wrong.

4. In terminal, change directory to the location of timimi.json and ensure that it has the appropriate permissions.

`cd $HOME/Library/Application Support/Mozilla/NativeMessagingHosts`
`chmod o+r  ./timimi.json`

5. Ensure that python3 is working in your system. If there is any other python program that depends on python3, ensure that it is running. 

If not, try issuing the command `brew link --overwrite python3` and try again.

**Comment by bnash** [comment]
Hello @ibnishak, thanks a lot for your response.
Regarding 1) and 2), I located the files timimi.py and timimi.json in
~/Library/Application Support/Mozilla/NativeMessagingHosts
There is also the file timimi.json-e

Regarding 3), this copy of timimi.json does appear to have the path set correctly.  My comment above referred to the copy in download directory.  Regarding 4), the file permissions appear to be fine.

Regarding 5), I'm not sure how to do this.  I tried the command `brew link --overwrite python3`, and it gave the result:
Error: No such keg: /usr/local/Cellar/python

**Comment by ibnishak** [comment]
In that case I recommend trying out other addons at this point. I will notify you when timimi works on Mac.

**Comment by bnash** [comment]
Ok, thanks for your help and I appreciate learning of updates. On the chance that I manage to get it to work, I will report this.

**Comment by ibnishak** [comment]
@denistestemale Can you try changing the shebang in `~/.mozilla/native-messaging-hosts/timimi.py` to **#!/usr/bin/env python3**

**Comment by denistestemale** [comment]
It did the trick, thanks @ibnishak ! It's all good now.
Cheers

**Comment by ibnishak** [comment]
Please check the new release and see if the problem persist. 
https://ibnishak.github.io/Timimi/#Installing%20Timimi

**Comment by ibnishak** [comment]
Closing as the issue pertains to older version. Several sources has verified that issue does not affect the current version.

**Comment by bnash** [comment]
It works for me now.  Many thanks @ibnishak !
