### ISSUE TITLE
Firefox, Ubuntu 20.04 and External HDD

### ISSUE THREAD

**Issue by sepremento** [ibnishak/Timimi#52]
Hi!

I've just switched to Ubuntu 20.04. Formerly I used Timimi for Firefox on Windows and stored my backup files on an external drive. Now it doesn't work. I get an error message: `Timimi save failed: attempt to postmessage on disconnected port`. I think there are several things which might be wrong, but I don't know which ones and I am not familiar with changing everything on Linux, so I need an advice:

* My path to the external drive could be wrong. I know that Linux mounts drives to `/media`, so I write my path in Timimi like this `/media/username/volume name/folder/`.
* There are also spaces and Russian symbols in the path, that might be interfering: `/media/username/русские символы/`. Should I use quotes? Should I rename volumes? I tried quotes though with no success, but maybe I was doing it wrong.
* My external drive is in NTFS. Can this be a problem?
* Maybe Linux prevents saving to external folder by default and I should use internal storage? As it might be obvious right now I am a complete newbie yet. However I tried to move a folder into the `~/Documents` and the same error was raised.
* Maybe I need some right or whatnot.

Thank you in advance!
Sincerely, Boris.

**Comment by ibnishak** [comment]
Hi Boris. Just confirming: You have installed the timimi backend for Ubuntu, right?

**Comment by sepremento** [comment]
My bad, haven't seen those instructions before. I've downloaded `timimi-2-1-1-Linux`, but my system tries to open it in a text editor. It is a shell script right?

**Comment by ibnishak** [comment]
Try the following commands in your terminal


cd ~/Downloads
chmod +x ./timimi-2-1-1-Linux
./timimi-2-1-1-Linux

**Comment by sepremento** [comment]
Installation went well. Now the backups are saved OK on the external HDD and all the changes are consequently saved in the backups, but the original file is not updating. I get the error message: `Error while saving data by Timimi Host. Please check error.log for details`. Made a search for that file and skimmed through help and haven't found where it is.

**Comment by ibnishak** [comment]
Check if there is a file called timimi.log in ~/.local/share/timimi or ~/.mozilla/nativemessaginghost

**Comment by ibnishak** [comment]
Also regarding non English characters in folder name, there is a bug in Tiddlywiki. Please see the [corresponding discussion in Google groups](https://groups.google.com/forum/m/#!topic/tiddlywiki/VWNouLAkhEs).

**Comment by sepremento** [comment]
Thank you! Changed volume and folder names, everything seems to work fine.
