### ISSUE TITLE
Timimi Save Problem (*and solution?) when URL includes "query" parameter

### ISSUE THREAD

**Issue by AnthonyMuscio** [ibnishak/Timimi#53]
Hi,

I am currently building a utility that needs to call tiddlywiki with additional parameters on the URL 
eg:
`file:///C:/Data/TW5/scratch/QuickUserTest.html?checkout=TW%20Tones?checkin=TW%20Tones?checkout=TW%20Tones`

However it seems once I load the wiki the existence of the query, ie that including and following the "?" is causing timimi's save to fail.

I expect the issue is using the value in $:/info/url/full rather than $:/info/url/pathname or something similar?

It may also be possible to remove the suffix $:/info/url/search from  $:/info/url/full 

Loving Timimi now on Chrome and FirefFox, I think its the best saver solutions.

Regards
Tony

**Comment by ibnishak** [comment]
As you know, this is not upto me. Timimi doesn't process the URL, it is tiddlyfox.js that does that. So if you want this functionality, you have to open this issue with tiddlywiki repo and get Jeremy to look into it. There is nothing I can do about this, sorry.

**Comment by AnthonyMuscio** [comment]
I did not actually know that. I could never understand why tiddlyfox was still mentioned.

Now I know, Thanks
