### ISSUE TITLE
Saving fails on Python 2.x

### ISSUE THREAD

**Issue by rmunn** [ibnishak/Timimi#6]
I believe I've figured out the reason behind #4. The `while True` loop for Python 2.x has the following code:

```python
        file=open(receivedMessage["path"],"w", encoding='utf-8')
        file.write("%s" % (receivedMessage["content"]))
        file.close()
```

But running `file = open("/tmp/example.json", "w", encoding='utf-8')` in Python 2 gives the error `TypeError: 'encoding' is an invalid keyword argument for this function`.

According to https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2, the simplest solution is to (in the Python 2 block) do `import io`, then use `io.open` instead of plain `open`. Then you just need to make sure that `receivedMessage["content"]` is a Unicode object rather than a string (simplest way is to do `file.write(unicode(receivedMessage["content"]))`) and the rest should work. (Tested locally on Mint 18 / Ubuntu 16.04 with Python 2.7).

**Comment by ibnishak** [comment]
The upcoming version of timimi ditches python completely for a compiled host written in golang. It also has abilities for backup. 

However, I will merge this after review later tonight.

**Comment by ibnishak** [comment]
PR Merged
