### ISSUE TITLE
Where is the action-launchscript widget?

### ISSUE THREAD

**Issue by amreus** [ibnishak/Timimi#65]
It's not in the repo.  Is it available somwhere? Thanks.

**Comment by TiddlyTweeter** [comment]
> It's not in the repo. Is it available somwhere? Thanks.

Ciao @amreus. My understanding that "action-launchscript" has been removed from the last version of Timimi that has evolved beyond just FireFox support.

Just FYI, _I still use_ it in the previous version of the plugin with Firefox to interact with the Windows OS. It still works well for my needs. BUT it means I still avoid updating Timimi and can only use it with FF.

MY understanding is that Riz felt action-launchscript could be a security issue of complexity once you outside FF. Too dangerous/complex to make universal. Something like that! But maybe he will answer yet.

Best wishes
TT
