### ISSUE TITLE
Chromebook / Chrome OS support?

### ISSUE THREAD

**Issue by sgyzetrov** [ibnishak/Timimi#68]
Hi,

I was wondering what would need to do to get Timimi working on Chrome OS/Chromebook, would a simple recompile do or additional things are needed. I am thinking about getting a Chromebook. If a simple recompile can get Timimi working on Chrome OS I am happy to compile it and make a PR and contribute to this project.

Regards,

**Comment by ibnishak** [comment]
Unfortunately, Chrome OS does not support native messaging hosts.

**Comment by sgyzetrov** [comment]
After some research I have a very 'ugly' workaround that I had in mind, will throw it out here and if I got the chance I will test it. So basically the idea is if we can't work with Chrome OS, and someone (right now, namely myself) really want to get Timimi working on a Chromebook, maybe one can try:

- Get Debian in Chrome OS (the developer mode allows this and two systems will co-exist like container). Then install firefox in debian and do all the Timimi setup. (This is a really ugly workaround, but it might just work if all one wants was to use TiddlyWiki+Timimi combo in a Chromebook. Why this combo? Because I really like the seamless first-in-first-out backup!).

I also have an idea (only a crude one that very likely not going to work), maybe reimplement the local host of Timimi to work without extension and just run it as a server in Debian, kinda like the [Minimal Ruby Server](https://tiddlywiki.com/#Saving%20via%20a%20Minimal%20Ruby%20Server), and in Chrome OS visit the tiddlywiki file using URL like (Debian container IP:port ) and see if saving/backup works.

**Comment by ibnishak** [comment]
I do not know enough about Chrome OS to make a suggestion. However if you are going to create and server with save and backup functionalities, it will be much easier to start with an exisiting webdav server and tweak it. Timimi has to comply with the restrictions and data exchange formats of native messaging. You can avoid all those hassles with webdav.

**Comment by sgyzetrov** [comment]
Thx, will check it out given time. Closed for now.
