### ISSUE TITLE
stucked on Starting to save wiki

### ISSUE THREAD

**Issue by arteteco** [ibnishak/Timimi#69]
Hello everyone,
just downloaded and run timimi v. 2.1.1 for linux on ubuntu 20.04 and installed the extension for Chrome, Version 90.0.4430.85 (Official Build) (64-bit)
Using Tiddlywiki 5.1.23

When I open a tiddlywiki file and press on save I have a message "Starting to save wiki" and the save button keeps being red, doesn't turn grey.
What am I doing wrong here?

Thanks!

EDIT: I tested it with a Tiddlywiki 5.1.13 and it is working flawlessly. Is this a problem with the most recent TW?

**Comment by Peter-8702** [comment]
> 
> 
> Hello everyone,
> just downloaded and run timimi v. 2.1.1 for linux on ubuntu 20.04 and installed the extension for Chrome, Version 90.0.4430.85 (Official Build) (64-bit)
> Using Tiddlywiki 5.1.23
> 
> When I open a tiddlywiki file and press on save I have a message "Starting to save wiki" and the save button keeps being red, doesn't turn grey.
> What am I doing wrong here?
> 
> Thanks!
> 
> EDIT: I tested it with a Tiddlywiki 5.1.13 and it is working flawlessly. Is this a problem with the most recent TW?

Looks like. I am using the former version and Timimi worked flawlessly for the past months, however with Firefox.

**Comment by arteteco** [comment]
I found the error, I guess it's a bug

# How to reproduce

Download an empty wiki from tiddlywiki.com
`./twexe empty.html`

The resulting wiki in `Settings > Saving > Tiddlyspot saver` will have `twexe` in the Wiki name field, so when saving tiddlywiki will do an attempt to save it (and fail), failing to save the wiki altogether.
I can't test on other OSes and version, but at least on my side I can reproduce it consistently
