### ISSUE TITLE
'timimi-2-1-1-Mac' File Not Opening On MacOS

### ISSUE THREAD

**Issue by monomycelium** [ibnishak/Timimi#77]
When I open the file I downloaded, it opens on TextEdit. If I select 'Open With', it does not show any other compatible application to open the file with. I am on macOS 12.1 on an M1 MacBook Air. Can anyone help?

**Comment by gnfisher** [comment]
You'll need to make the script executable then run it.
Open terminal app then run these commands. They assume you downloaded the file into your Downloads folder.

```
cd ~/Downloads
chmod +x timimi-2-1-1-Mac
./timimi-2-1-1-Mac
```

**Comment by monomycelium** [comment]
On 10 January, I had no idea how to use Terminal, leading to my stupid question. I apologise for taking up your time to execute a script!
