### ISSUE TITLE
Serious error with Timimi

### ISSUE THREAD

**Issue by AnthonyMuscio** [ibnishak/Timimi#80]
@ibnishak I am hoping you could make a small fix to Timimi which has caused me some confusion a number of times, until I rediscover a bug in Timimi.

The Problem is if you use a url address with anything after the path eg `URL?mode=edit`
* Providing `URL#tiddlername` is OK. and allows saving

I am testing this on other savers and will report if I observe any other cases of this.

I think all that needs to be done is to parse the URL and only use everything that occurs before the "?" as the filename/address
* if "?" is in the URL 
* Please note I may have reported this earlier but could not locate it.
* I believe this is necessary to adhere to standard URI protocols

Thanks in advance

**Comment by ibnishak** [comment]
This is not a timimi bug, but a tiddlywiki bug. URL parsing is done by the core and passed to timimi. Please notify in the Tiddlywiki repo.
